services:
    kali:
        image: kalilinux/kali-rolling
        container_name: kali
        environment:
            USERNAME: "root"
            PASSWORD: "toor"
            RAM_SIZE: "4G"
            CPU_CORES: "4"
        devices:
            - /dev/kvm
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        ports:
            - "8006:8006"
        tty: true
        stdin_open: true
        restart: unless-stopped
